/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "nova.api.": [
        {
            "name": "resource",
            "required": true
        },
        {
            "name": "resourceId",
            "required": true
        },
        {
            "name": "relatedResource",
            "required": true
        }
    ],
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "nova.pages.login": [],
    "nova.login": [],
    "nova.logout": [],
    "nova.pages.password.email": [],
    "nova.password.email": [],
    "nova.pages.password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "nova.password.reset": [],
    "nova.pages.403": [],
    "nova.pages.404": [],
    "nova.pages.home": [],
    "nova.pages.dashboard": [],
    "nova.pages.dashboard.custom": [
        {
            "name": "name",
            "required": true
        }
    ],
    "nova.pages.index": [
        {
            "name": "resource",
            "required": true
        }
    ],
    "nova.pages.create": [
        {
            "name": "resource",
            "required": true
        }
    ],
    "nova.pages.detail": [
        {
            "name": "resource",
            "required": true
        },
        {
            "name": "resourceId",
            "required": true
        }
    ],
    "nova.pages.edit": [
        {
            "name": "resource",
            "required": true
        },
        {
            "name": "resourceId",
            "required": true
        }
    ],
    "nova.pages.replicate": [
        {
            "name": "resource",
            "required": true
        },
        {
            "name": "resourceId",
            "required": true
        }
    ],
    "nova.pages.lens": [
        {
            "name": "resource",
            "required": true
        },
        {
            "name": "lens",
            "required": true
        }
    ],
    "nova.pages.attach": [
        {
            "name": "resource",
            "required": true
        },
        {
            "name": "resourceId",
            "required": true
        },
        {
            "name": "relatedResource",
            "required": true
        }
    ],
    "nova.pages.edit-attached": [
        {
            "name": "resource",
            "required": true
        },
        {
            "name": "resourceId",
            "required": true
        },
        {
            "name": "relatedResource",
            "required": true
        },
        {
            "name": "relatedResourceId",
            "required": true
        }
    ],
    "dashboard": [],
    "admin\/dashboard": [],
    "portal\/dashboard": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": []
}
}
export {};
