<?php

return [
    'Elementary Schools' => [
        'Armstrong, Burnaby',
        'Betty Huff, Surrey',
        'Britannia Community, Vancouver',
        'Sir Guy Carleton, Vancouver',
        'Cameron, Burnaby',
        'Cedar Hills, Surrey',
        'Chaffey-Burke, Burnaby',
        'Crosstown, Vancouver',
        'David Brankin, Surrey',
        'Douglas Road, Burnaby',
        'Edmonds Community, Burnaby',
        'Sir Sandford Fleming, Vancouver',
        'Forsyth Road Elementary, Surrey',
        'Graham Bruce, Vancouver',
        'Grandview, Vancouver',
        'Green Timbers, Surrey',
        'Hastings, Vancouver',
        'James Ardiel, Surrey',
        'John Henderson, Vancouver',
        'Hjorth Road, Surrey',
        'Kingvig W.E. Elementary, Surrey',
        'Kirkbride, Surrey',
        'Ecole Inman, Burnaby',
        'David Livingston, Vancouver',
        'Lord Beaconsfield, Vancouver',
        'Sir William MacDonald, Vancouver',
        'Ecole Marlborough, Burnaby',
        'Maywood Community, Burnaby',
        'Matthew, AHP Elementary, Surrey',
        'Dr. H.H. MacCorkindale, Vancouver',
        'Morley, Burnaby',
        'Mount Pleasant, Vancouver',
        'Florence Nightingale, Vancouver',
        'John Norquay, Vancouver',
        'Old Yale Road, Surrey',
        'David Oppenheimer, Vancouver',
        'Prince Charles, Surrey',
        'Riverdale, Surrey',
        'Royal Heights, Surrey',
        'Second Street, Burnaby',
        'South Slope, Burnaby',
        'Lord Selkirk, Vancouver',
        'Admiral Seymour, Vancouver',
        'Simon Cunningham, Surrey',
        'South Slope, Burnaby',
        'Lord Strathcona, Vancouver',
        'Stride, Vancouver',
        'Tecumseh Park, Vancouver',
        'Thunderbird, Vancouver',
        'Tillicum Annex, Vancouver',
        'Twelfth Avenue, Burnaby',
        'Windsor, Burnaby',
        'Woodward K.B, Surrey',
    ],
    'Secondary Schools' => [
        'Burnaby South, Burnaby',
        'Britannia, Vancouver',
        'Gladstone, Vancouver',
        'Killarney, Vancouver',
        'Templeton, Vancouver',
        'Sir Charles Tupper, Vancouver',
        'Vancouver Technical, Vancouver',
        'Windermere, Vancouver',
    ],
    'Other Locations' => [
        'Strathcona Community Centre',
        'Musqueam Indian Reserve',
        'Swangard Stadium',
    ]
];